/* tslint:disable */
/* eslint-disable */

/* auto-generated by NAPI-RS */

export const INVALID_INDEX: number
export function connectFour(v: Uint8Array, maximumDepth?: number | undefined | null): number
export function ticTacToe(v: Uint8Array): number
