/* tslint:disable */
/* eslint-disable */

/* auto-generated by NAPI-RS */

export const enum Player {
	Unset = 0,
	Human = 1,
	Machine = 2
}
export const INVALID_INDEX: number;
export class ConnectFour {
	constructor(values?: Uint8Array | undefined | null);
	get board(): Uint8Array;
	available(column: number): boolean;
	get finished(): boolean;
	add(column: number, player: Player): boolean;
	getBestMove(depth?: number | undefined | null): number;
}
export class TicTacToe {
	constructor(values?: Uint8Array | undefined | null);
	get board(): Uint8Array;
	available(cell: number): boolean;
	get finished(): boolean;
	add(cell: number, player: Player): boolean;
	getBestMove(depth?: number | undefined | null): number;
}
