/* tslint:disable */
/* eslint-disable */

/* auto-generated by NAPI-RS */

export const enum Players {
	Unset = 0,
	Player = 1,
	Machine = 2
}
export const INVALID_INDEX: number;
export function ticTacToe(v: Uint8Array): number;
export class ConnectFour {
	constructor();
	static withCells(values: Uint8Array): ConnectFour;
	getBoard(): Uint8Array;
	available(column: number): boolean;
	add(column: number, player: Players): boolean;
	getBestMove(depth?: number | undefined | null): number;
}
