name: Lint

on:
  push:
    branches:
      - main
    tags-ignore:
      - '**'
  pull_request:
concurrency:
  group: ${{ github.workflow }}-${{ github.ref }}
  cancel-in-progress: true
jobs:
  lint:
    name: Lint
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v5

      - name: Setup node
        uses: actions/setup-node@v5
        with:
          node-version: 22
          cache: 'yarn'

      - name: Install
        uses: dtolnay/rust-toolchain@nightly
        with:
          components: clippy, rustfmt

      - name: Install dependencies
        run: yarn install

      - name: ESLint
        run: yarn lint

      - name: Cargo fmt
        run: cargo +nightly fmt -- --check

      - name: Clippy
        run: cargo clippy
